### ISSUE TITLE
Tags/Categories/Comments are not working in the latest release

### ISSUE THREAD

**Issue by TDabasinskas** [ProjectNami/projectnami#19]
I can set tags and categories for posts, but it seems there are issues querying them:

* Tag Cloud is empty
* Category menu does not automatically include categories
* Category manager in Admin panel shows that each category has 0 posts, even though that is not true
* Comment count for each post is shown as zero, (though, the comments are displayed correctly)

I am using the latest version. Please let me know if you need additional details.

**Comment by TDabasinskas** [comment]
Please find PHP Error Log generated after replacing a single post page:

`[23-Apr-2015 17:48:42 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'wp_wp_rp_tags'. Code - 208 for query SELECT DISTINCT(label) FROM wp_wp_rp_tags WHERE post_id=588 ORDER BY weight desc; made by require('D:\home\site\wwwroot\wp-blog-header.php'), require_once('D:\home\site\wwwroot\wp-includes\template-loader.php'), include('D:\home\site\wwwroot\wp-content\themes\dabasinskas\single.php'), get_header, locate_template, load_template, require_once('D:\home\site\wwwroot\wp-content\themes\dabasinskas\header.php'), wp_head, do_action('wp_head'), call_user_func_array, wp_rp_head_resources
[23-Apr-2015 17:48:42 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'wp_wp_rp_tags'. Code - 208 for query SELECT label FROM wp_wp_rp_tags WHERE post_id=588; made by require('D:\home\site\wwwroot\wp-blog-header.php'), require_once('D:\home\site\wwwroot\wp-includes\template-loader.php'), include('D:\home\site\wwwroot\wp-content\themes\dabasinskas\single.php'), get_template_part, locate_template, load_template, require('D:\home\site\wwwroot\wp-content\themes\dabasinskas\content-single.php'), wp_related_posts, wp_get_related_posts, wp_rp_get_related_posts, wp_rp_fetch_posts_and_title, wp_rp_append_posts, call_user_func, wp_rp_fetch_related_posts_v2
[23-Apr-2015 17:48:42 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'wp_wp_rp_tags'. Code - 208 for query INSERT INTO wp_wp_rp_tags (post_id, post_date, label, weight)
				VALUES (588, '2012-07-09 14:30:06', 'P_award', 10.000000), (588, '2012-07-09 14:30:06', 'P_mvp', 10.000000), (588, '2012-07-09 14:30:06', 'P_windows expert', 10.000000), (588, '2012-07-09 14:30:06', 'C_achieving', 5.000000), (588, '2012-07-09 14:30:06', 'A_microsoft', 2.000000), (588, '2012-07-09 14:30:06', 'A_window', 2.000000), (588, '2012-07-09 14:30:06', 'A_award', 2.000000), (588, '2012-07-09 14:30:06', 'A_toma', 2.000000), (588, '2012-07-09 14:30:06', 'A_commun', 2.000000), (588, '2012-07-09 14:30:06', 'A_mvp', 2.000000), (588, '2012-07-09 14:30:06', 'A_world', 2.000000), (588, '2012-07-09 14:30:06', 'A_real', 2.000000), (588, '2012-07-09 14:30:06', 'A_activ', 2.000000), (588, '2012-07-09 14:30:06', 'A_8', 2.000000), (588, '2012-07-09 14:30:06', 'A_manag', 2.000000), (588, '2012-07-09 14:30:06', 'A_technic', 2.000000), (588, '2012-07-09 14:30:06', 'A_releas', 2.000000), (588, '2012-07-09 14:30:06', 'A_high', 2.000000), (588, '2012-07-09 14:30:06', 'A_a', 2.000000); made by require('D:\home\site\wwwroot\wp-blog-header.php'), require_once('D:\home\site\wwwroot\wp-includes\template-loader.php'), include('D:\home\site\wwwroot\wp-content\themes\dabasinskas\single.php'), get_template_part, locate_template, load_template, require('D:\home\site\wwwroot\wp-content\themes\dabasinskas\content-single.php'), wp_related_posts, wp_get_related_posts, wp_rp_get_related_posts, wp_rp_fetch_posts_and_title, wp_rp_append_posts, call_user_func, wp_rp_fetch_related_posts_v2, wp_rp_generate_tags
[23-Apr-2015 17:48:42 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'wp_wp_rp_tags'. Code - 208 for query SELECT count(post_id) from (SELECT post_id FROM wp_wp_rp_tags group by post_id) t; made by require('D:\home\site\wwwroot\wp-blog-header.php'), require_once('D:\home\site\wwwroot\wp-includes\template-loader.php'), include('D:\home\site\wwwroot\wp-content\themes\dabasinskas\single.php'), get_template_part, locate_template, load_template, require('D:\home\site\wwwroot\wp-content\themes\dabasinskas\content-single.php'), wp_related_posts, wp_get_related_posts, wp_rp_get_related_posts, wp_rp_fetch_posts_and_title, wp_rp_append_posts, call_user_func, wp_rp_fetch_related_posts_v2
[23-Apr-2015 17:48:42 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Column 'wp_posts.ID' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. Code - 8120 for query SELECT TOP 5 p.ID, p.post_title, p.post_content,p.post_excerpt, p.post_date, p.comment_count, count(t_r.object_id) as cnt 
				FROM wp_term_taxonomy t_t, wp_term_relationships t_r, wp_posts p
				WHERE t_t.taxonomy ='post_tag'
					AND t_t.term_taxonomy_id = t_r.term_taxonomy_id
					AND t_r.object_id = p.ID
					AND (t_t.term_id IN ('78', '79', '80'))
					AND p.ID NOT IN (588)
					AND p.post_status = 'publish'
					AND p.post_type = 'post'
					AND p.post_date_gmt < '2015-04-23 17:48:42' GROUP BY t_r.object_id
				ORDER BY cnt DESC, p.post_date_gmt DESC  made by require('D:\home\site\wwwroot\wp-blog-header.php'), require_once('D:\home\site\wwwroot\wp-includes\template-loader.php'), include('D:\home\site\wwwroot\wp-content\themes\dabasinskas\single.php'), get_template_part, locate_template, load_template, require('D:\home\site\wwwroot\wp-content\themes\dabasinskas\content-single.php'), wp_related_posts, wp_get_related_posts, wp_rp_get_related_posts, wp_rp_fetch_posts_and_title, wp_rp_append_posts, call_user_func, wp_rp_fetch_related_posts
[23-Apr-2015 17:48:43 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:6:{i:0;s:32:"tlc_lock_5539307b4a46e1.02624286";i:1;s:36:"twp_e3fc9391ca5c47839af1b73803e6aa5a";i:2;i:300;i:3;a:2:{i:0;O:15:"wpTwitterWidget":14:{s:34:"'. Code - 105 for query IF NOT EXISTS (SELECT * FROM [wp_options] WHERE [option_name] = '_transient_tlc_up__f808e1c4886e4260ec26981336e169c9') INSERT INTO [wp_options] ([option_name], [option_value], [autoload]) VALUES ('_transient_tlc_up__f808e1c4886e4260ec26981336e169c9', 'a:6:{i:0;s:32:"tlc_lock_5539307b4a46e1.02624286";i:1;s:36:"twp_e3fc9391ca5c47839af1b73803e6aa5a";i:2;i:300;i:3;a:2:{i:0;O:15:"wpTwitterWidget":14:{s:34:"
[23-Apr-2015 17:49:26 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'wp_wp_rp_tags'. Code - 208 for query SELECT DISTINCT(label) FROM wp_wp_rp_tags WHERE post_id=5339 ORDER BY weight desc; made by require('D:\home\site\wwwroot\wp-blog-header.php'), require_once('D:\home\site\wwwroot\wp-includes\template-loader.php'), include('D:\home\site\wwwroot\wp-content\themes\dabasinskas\index.php'), get_header, locate_template, load_template, require_once('D:\home\site\wwwroot\wp-content\themes\dabasinskas\header.php'), wp_head, do_action('wp_head'), call_user_func_array, wp_rp_head_resources
[23-Apr-2015 17:49:27 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'a:6:{i:0;s:32:"tlc_lock_553930a71dca84.16426351";i:1;s:36:"twp_e3fc9391ca5c47839af1b73803e6aa5a";i:2;i:300;i:3;a:2:{i:0;O:15:"wpTwitterWidget":14:{s:34:"'. Code - 105 for query IF NOT EXISTS (SELECT * FROM [wp_options] WHERE [option_name] = '_transient_tlc_up__f808e1c4886e4260ec26981336e169c9') INSERT INTO [wp_options] ([option_name], [option_value], [autoload]) VALUES ('_transient_tlc_up__f808e1c4886e4260ec26981336e169c9', 'a:6:{i:0;s:32:"tlc_lock_553930a71dca84.16426351";i:1;s:36:"twp_e3fc9391ca5c47839af1b73803e6aa5a";i:2;i:300;i:3;a:2:{i:0;O:15:"wpTwitterWidget":14:{s:34:"`

**Comment by patrickebates** [comment]
I can confirm the problem with post counts on Categories being incorrect.  I will look into root cause shortly.

As for the errors above, I'm not sure what is going on right now.  It almost looks like your table prefix is being doubled up?

**Comment by TDabasinskas** [comment]
Is the tags/category list not being displayed also relates to the post count problem you are aware about?

As for the logs, thank you. It was a buggy plugin. I removed it and the logs above, as they don't relate to the issue.

**Comment by patrickebates** [comment]
I've identified the source of the problem, and we're working on a fix to include in the merge with 4.2.0 very soon.

**Comment by TDabasinskas** [comment]
Perfect. Thank you!

**Comment by patrickebates** [comment]
If you are interested in testing the fix, I've just pushed what we think will solve the problem to the Master branch.

Master currently includes WP 4.2.0 and has PN version 1.0

**Comment by TDabasinskas** [comment]
I have updated by installation from the __latest__ (from the commit log, I see the latest changes from __master__ are already merged), but the issue still persists.

**Comment by patrickebates** [comment]
The issue with counts should begin to repair itself as additional actions are taken with those categories, posts and tags (it will trigger the updating of those values).  In our testing, this also appeared to resolve issues with items missing from Tag Cloud.

If you don't have enough activity in your back-end to trigger these updates fast enough, I can look at putting together some sort of repair/update script.

**Comment by TDabasinskas** [comment]
I have just tried creating a new tag, deleting it, creating a new category, deleting it and renaming an existing category, but it doesn't seem to help.

**Comment by patrickebates** [comment]
You should only have to update one post in each category and tag for it to work.  The query to store the count does a full search against the categories and tags every time it is called.

**Comment by TDabasinskas** [comment]
Got it. Thanks again for getting this fixed!
